
title: Shanelle Wikramanayake
author: Shanelle Wikramanayake
email: shanelle.wikramanayake.101@my.csun.edu
domain: shanellewiks.github.io
baseurl: /shanellewiks.github.io/ # the subpath of your site, e.g. /blog
url: https://shanellewiks.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SAWikramanayake
github_username:  Shanellewiks
show_downloads: f


# Layout 


description: >- # this means to ignore newlines until "baseurl:"
  "I am a graduate student interested in the evolutionary ecology of reptiles and amphibians in tropical rainforests. My undergradute research 
  was on the population structure and genetic diversity of the endemic and endangered Rough-nosed horned lizard of Sri Lanka. 
  My current M.S. thesis work explored the neurological basis of mate choice in the highly variable Red-eyed Treefrog of Costa Rica."
  
  
# Build settings
remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
